Citizen.CreateThread(function()
      AddTextEntry("one77", "Aston Martin One-77")
      AddTextEntry("LibertyWalk", "Audi R8 Liberty Walk")
      AddTextEntry("bdivo", "Bugatti Divo")
      AddTextEntry("contgt13", "Bentley Continental GT")
      AddTextEntry("m3e30", "BMW M3 E30")
      AddTextEntry("2017CHIRON", "Bugatti Chiron")
      AddTextEntry("BUGATTI", "Bugatti Veyron")
      AddTextEntry("CHEVELLESS", "Chevrolet Chevelle SS 454")
      AddTextEntry("C7", "Chevrolet Corvette C7")
      AddTextEntry("CHARGER", "Dodge Charger SRT")
      AddTextEntry("BERLINETTA", "Ferrari F12 Berlinetta")
      AddTextEntry("APERTA", "Ferrari LaFerrari")
      AddTextEntry("MUSTANG", "2015 Ford Mustang GT")
      AddTextEntry("P1", "McLaren P1")
      AddTextEntry("G65", "Mercedes G65 AMG")
      AddTextEntry("COOPER15", "Mini Cooper S")
      AddTextEntry("evo9", "Mitsubishi Lancer Evolution IX")
      AddTextEntry("370Z", "Nissan 370Z Nismo Z34")
      AddTextEntry("gtr", "Nissan GTR R35")
      AddTextEntry("CAYENNE", "Porsche Cayenne Turbo S")
      AddTextEntry("eleanor", "1967 Shelby GT500")
      AddTextEntry("tmax", "TMax 500")
      AddTextEntry("jza80", "Toyota Supra JZA80")
      AddTextEntry("dodgeEMS", "Dodge EMS")
      AddTextEntry("rs6", "Audi RS6 C7")
      AddTextEntry("CENTENARIOR", "Lamborghini Centenario")
      AddTextEntry("nero2", "Bugatti Vision GT")
      AddTextEntry("RAPTOR F-150", "Ford Raptor F-150")
      AddTextEntry("sc18", "Lamborghini SC18 Alston 2019")
      AddTextEntry("ferrari812", "Ferrari 812 Superfast 2018")
      AddTextEntry("p1gtr", "McLaren P1 GTR")
      AddTextEntry("m5police", "BMW M5")
end)