---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 28/12/2019 13:46
---

RMenu.Add('ragelevel', 'main', RageUI.CreateMenu("RageLevel", "~b~ALL RAGE-LEVEL CONTENT LOCATION."))

local MLO = {
    { x = -1320.36, y = -834.51, z = 16.96, label = "Gruppe Sechs", description = nil },
    { x = -545.01, y = -206.36, z = 38.21, label = "City Hall", description = nil },
    { x = 325.15, y = -1069.87, z = 29.46, label = "Pharmacy Pills", description = nil },
    { x = 289.86, y = -961.63, z = 29.42, label = "Drusillas", description = nil },
    { x = 360.59, y = -596.92, z = 28.65, label = "Pillbox Hospital", description = nil },
    { x = 357.08, y = -1581.74, z = 29.29, label = "Davis Sheriff", description = nil },
    { x = -658.53, y = -852.76, z = 23.99, label = "DigitalDen", description = nil },
    { x = -1640.8, y = -1007.54, z = 13.02, label = "Delperro Police Station", description = nil },
    { x = -252.17, y = -338.34, z = 29.96, label = "Galaxy Nightclub Rockford Plaza", description = nil },
    { x = -331.08, y = -163.27, z = 102.73, label = "Cinemavine", description = nil },
    { x = -431.69, y = 254.74, z = 83.02, label = "Split Sides Comedy Club", description = nil },
    { x = -630.31, y = 251.61, z = 81.58, label = "Bean Machine", description = nil },
    { x = -907.109, y = -2046.3, z = 8.69, label = "La Puerta Car dealer", description = nil },
    { x = -606.55, y = -932.84, z = 23.86, label = "Weazel News", description = nil },
    { x = -961.49, y = -1483.84, z = 4.45, label = "La Puerta Temple", description = nil },
    { x = -809.56, y = -1332.16, z = 4.59, label = "La Puerta Boat shop", description = nil },
    { x = -809.95, y = -227.79, z = 36.65, label = "Luxury Autos", description = nil },
    { x = 246.39, y = -382.61, z = 44.07, label = "Court House", description = nil },
    { x = 1171.21, y = -282.85, z = 69.09, label = "Gabrielas Market", description = nil },
    { x = 879.72, y = 44.08, z = 78.59, label = "Casino Diamond", description = nil },
    { x = 1369.82, y = 1147.48, z = 113.76, label = "Madrazo Ranch", description = nil },
    { x = 1855.3, y = 2585.86, z = 45.67, label = "Prison Lobby", description = nil },
    { x = 1691.67, y = 2585, z = 45.67, label = "Prison Cells", description = nil },
    { x = 1766.15, y = 2669.27, z = 45.56, label = "Prison Cells 2", description = nil },
    { x = 1839.85, y = 3667.95, z = 33.68, label = "Sandy Shores Hospital", description = nil },
    { x = 1858.21, y = 3677.01, z = 33.68, label = "Sandy Shores Sheriff", description = nil },
    { x = 1588, y = 6444.21, z = 25.15, label = "Pops Diner", description = nil },
    { x = -237.48, y = 6333.02, z = 32.42, label = "Paleto Bay Hospital", description = nil },
    { x = -437.71, y = 6021.98, z = 31.49, label = "Paleto Bay Sheriff", description = nil },
    { x = -383.81, y = 6122.5, z = 31.48, label = "Paleto Bay Fire Station", description = nil },
    { x = -1095.97, y = 4942.76, z = 218.35, label = "The Barn", description = nil },
    { x = -1873.18, y = 2024.36, z = 139.11, label = "Marlow Vineyard", description = nil },
    { x = -123.99, y = 980.92, z = 235.81, label = "Vinewood Mansion", description = nil },
    { x = 91.64, y = -212.82, z = 54.49, label = "Mimis Burger", description = nil },
    { x = 978.8, y = -123.43, z = 74.05, label = "The Lost MC 1", description = nil },
    { x = 980.6, y = -109.46, z = 74.35, label = "The Lost MC 2", description = nil },
    { x = 110.03, y = -1949.57, z = 20.66, label = "Groove Street House with Warehouses", description = nil },
    { x = 132.73, y = -2003.52, z = 18.2, label = "Groove Street Garage", description = nil },
    { x = 87.44, y = -1957.09, z = 20.75, label = "Groove Street House 2", description = nil },
    { x = 247.35, y = -1815.7, z = 27.01, label = "Groove Street House 3", description = nil },
    { x = 333.17, y = -2026.83, z = 20.88, label = "Vagos Barrio", description = nil },
    { x = 484.23, y = -1889.57, z = 25.39, label = "Vagos Garage", description = nil },
    { x = 403.37, y = -1910.65, z = 24.57, label = "Taco Libre", description = nil },
    { x = 135.12, y = -1592.23, z = 34.24, label = "Families House 1", description = nil },
    { x = -13.92, y = -1446.68, z = 30.65, label = "Families House 2", description = nil },
    { x = 1223.66, y = 2718.59, z = 38.01, label = "Larrys", description = nil },
    { x = 922.038, y = -2328.582, z = 34.66, label = "Import Garage", description = nil },
    { x = 1928.355, y = 4622.056, z = 46.42, label = "Askhammer", description = nil },
    { x = -1508.253, y = 1507.484, z = 113.645, label = "Whitewater", description = nil },
    { x = 715.99, y = -1088.62, z = 21.76, label = "Los Santos Customs", description = nil },
    { x = 370.634, y = -925.946, z = 28.404, label = "Church", description = nil },
    { x = 1993.58, y = 3058.68, z = 46.45, label = "Yellow Jack", description = nil },
    { x = -652.07, y = -291.57, z = 34.83, label = "iFruit", description = nil },
    { x = -1403.928, y = -438.58, z = 37.0587, label = "Doctor Cabinet", description = nil },
    { x = -1403.928, y = -438.58, z = 37.0587, label = "Autoschool", description = nil },
    { x = -1403.928, y = -438.58, z = 37.0587, label = "Marabunta Garage", description = nil },
    { x = -1403.928, y = -438.58, z = 37.0587, label = "Marabunta House", description = nil },
    { x = 225.73, y = 361.14, z = 105.96, label = "Autoschool", description = nil },
    { x = 1454.3, y = -1683.11, z = 66.04, label = "Marabunta", description = nil },
    { x = 2479.26800000, y = -273.87380000, z = -59.28285000, label = "Casino - HEIST", description = nil },
    { x = 2730.00000000, y = -380.00000000, z = -50.00000000, label = "Casino - ARCADE / BAR", description = nil },
    { x = 2697.61500000, y = -376.38910000, z = -56.46193000, label = "Casino - PLAN INTERIOR", description = nil },
    { x = 2523.36100000, y = -270.00000000, z = -59.72315000, label = "Casino - BACK", description = nil },
    { x = 2504.38600000, y = -257.21960000, z = -40.12296000, label = "Casino - HOTEL", description = nil },
    { x = 2553.96300000, y = -281.38050000, z = -65.72305000, label = "Casino - LOADING", description = nil },
    { x = 2488.34800000, y = -267.36370000, z = -71.64563000, label = "Casino - VAULT", description = nil },
    { x = 2519.87600000, y = -255.30270000, z = -25.11497000, label = "Casino - UTILITY", description = nil },
    { x = 2497.70700000, y = -312.77050000, z = -71.46999000, label = "Casino - TUNNEL", description = nil },
    { x = 2572.88800000, y = -253.43860000, z = -65.65990000, label = "Casino - SHAFT", description = nil },
};

local function FreezePlayer(id, freeze)
    local player = id
    SetPlayerControl(player, not freeze, false)
    local ped = GetPlayerPed(player)
    if not freeze then
        if not IsEntityVisible(ped) then
            SetEntityVisible(ped, true)
        end
        if not IsPedInAnyVehicle(ped) then
            SetEntityCollision(ped, true)
        end
        FreezeEntityPosition(ped, false)
        SetPedCanBeTargetted(ped, false)
        SetPlayerInvincible(player, false)
    else
        if IsEntityVisible(ped) then
            SetEntityVisible(ped, false)
        end
        SetEntityCollision(ped, false)
        FreezeEntityPosition(ped, true)
        SetPedCanBeTargetted(ped, true)
        SetPlayerInvincible(player, true)
        if not IsPedFatallyInjured(ped) then
            ClearPedTasksImmediately(ped)
        end
    end
end

local function SetCoords(entity, isInterior, x, y, z, h, unFreeze, fadeIn, fadeOut)
    fadeIn = fadeIn or false
    fadeOut = fadeOut or false
    if (fadeIn) then
        if not IsScreenFadedOut() then
            DoScreenFadeOut(1200)
        end
    end
    entity = entity or GetPlayerPed(-1)
    SetEntityCoords(entity, x, y, z)
    RequestCollisionAtCoord(x, y, z)
    FreezePlayer(PlayerId(), true)
    if (isInterior) then
        LoadInterior(isInterior)
        while not IsInteriorReady(isInterior) do
            Citizen.Wait(1)
        end
    end
    while not HasCollisionLoadedAroundEntity(entity) do
        Citizen.Wait(1)
    end
    if (unFreeze) then
        FreezePlayer(PlayerId(), false)
    end
    SetEntityHeading(entity, h)
    if (fadeOut) then
        if not IsScreenFadedIn() then
            DoScreenFadeIn(1200)
        end
    end
    return true
end

local function ShowLoadingPrompt(showText, showType, showTime)
    Citizen.CreateThreadNow(function()
        Citizen.Wait(0)
        BeginTextCommandBusyString("STRING")
        AddTextComponentString(showText)
        EndTextCommandBusyString(showType)
        Citizen.Wait(showTime)
        if (IsLoadingPromptBeingDisplayed()) then
            RemoveLoadingPrompt()
        end
    end)
end

RageUI.CreateWhile(1.0, function()
    if IsControlJustPressed(1, 166) then
        RageUI.Visible(RMenu:Get('ragelevel', 'main'), not RageUI.Visible(RMenu:Get('ragelevel', 'main')))
    end
    if RageUI.Visible(RMenu:Get('ragelevel', 'main')) then
        RageUI.DrawContent({ header = true, glare = true, instructionalButton = true }, function()
            ---Items
            for key, value in pairs(MLO) do
                RageUI.Button(value.label, value.description, {  }, true, function(Hovered, Active, Selected)
                    if (Selected) then
                        if not (GetInteriorAtCoords(value.x, value.y, value.z)) then
                            SetCoords(GetPlayerPed(-1), true, value.x, value.y, value.z - 1.0, value.heading, true, false, false)
                        else
                            SetCoords(GetPlayerPed(-1), false, value.x, value.y, value.z - 1.0, value.heading, true, false, false)
                        end
                        ShowLoadingPrompt(string.format("Teleporting to %s successfully", value.name), 1, 1500)
                    end
                end)
            end
        end, function()
            --- Panel
        end)
    end
end)