---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 28/12/2019 13:46
---
fx_version 'adamant'
games { 'gta5' }

dependency 'rage-level'

client_scripts {
    "RageUI/src/RMenu.lua",
    "RageUI/src/menu/RageUI.lua",
    "RageUI/src/menu/Menu.lua",
    "RageUI/src/menu/MenuController.lua",

    "RageUI/src/components/*.lua",

    "RageUI/src/menu/elements/*.lua",

    "RageUI/src/menu/items/*.lua",

    "RageUI/src/menu/panels/*.lua",

    "RageUI/src/menu/panels/*.lua",
    "RageUI/src/menu/windows/*.lua",
}

client_scripts {
    'client.lua',
}
